[package]
name = "tw_groestlcoin"
version = "0.1.0"
edition = "2021"

[dependencies]
tw_base58_address = { path = "../../tw_base58_address" }
tw_bitcoin = { path = "../../chains/tw_bitcoin" }
tw_coin_entry = { path = "../../tw_coin_entry" }
tw_encoding = { path = "../../tw_encoding" }
tw_hash = { path = "../../tw_hash" }
tw_keypair = { path = "../../tw_keypair" }
tw_memory = { path = "../../tw_memory" }
tw_proto = { path = "../../tw_proto" }
tw_utxo = { path = "../../frameworks/tw_utxo" }
