[package]
name = "tw_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
derive-syn-parse = "0.2.0"
proc-macro2 = "1.0.106"
quote = "1.0.44"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.21"
syn = { version = "2.0.117", features = ["full"] }
