[package]
name = "tw_pactus"
version = "0.1.0"
edition = "2021"

[dependencies]
bech32 = "0.9.1"
byteorder = "1.4"
tw_coin_entry = { path = "../../tw_coin_entry" }
tw_keypair = { path = "../../tw_keypair" }
tw_memory = { path = "../../tw_memory" }
tw_proto = { path = "../../tw_proto" }
tw_hash = { path = "../../tw_hash" }
tw_encoding = { path = "../../tw_encoding" }

[dev-dependencies]
tw_encoding = { path = "../../tw_encoding" }
hex = "0.4.3"
