[package]
name = "tw_solana"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "3.0.0"
borsh = { version = "1.6.0", features = ["derive"] }
lazy_static = "1.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tw_coin_entry = { path = "../../tw_coin_entry" }
tw_encoding = { path = "../../tw_encoding" }
tw_hash = { path = "../../tw_hash" }
tw_keypair = { path = "../../tw_keypair" }
tw_memory = { path = "../../tw_memory" }
tw_misc = { path = "../../tw_misc" }
tw_number = { path = "../../tw_number" }
tw_proto = { path = "../../tw_proto" }
