[package]
name = "tw_ripple"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal = "0.4.10"
byteorder = "1.5"
lazy_static = "1.5.0"
serde = "1.0"
serde_json = "1.0"
strum_macros = "0.28"
tw_base58_address = { path = "../../tw_base58_address" }
tw_coin_entry = { path = "../../tw_coin_entry" }
tw_encoding = { path = "../../tw_encoding" }
tw_hash = { path = "../../tw_hash" }
tw_keypair = { path = "../../tw_keypair" }
tw_memory = { path = "../../tw_memory" }
tw_misc = { path = "../../tw_misc", features = ["serde"] }
tw_proto = { path = "../../tw_proto" }
