[package]
name = "tw_polymesh"
version = "0.1.0"
edition = "2021"

[dependencies]
tw_coin_entry = { path = "../../tw_coin_entry" }
tw_encoding = { path = "../../tw_encoding" }
tw_hash = { path = "../../tw_hash" }
tw_keypair = { path = "../../tw_keypair" }
tw_memory = { path = "../../tw_memory" }
tw_number = { path = "../../tw_number" }
tw_proto = { path = "../../tw_proto" }
tw_scale = { path = "../../tw_scale" }
tw_ss58_address = { path = "../../tw_ss58_address" }
tw_substrate = { path = "../../frameworks/tw_substrate" }
