name: Codegen-v2 Tests

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

env:
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  test:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:
      - uses: trustwallet/github-actions-proxy/actions/checkout@main
      - name: Install system dependencies
        run: |
          tools/install-sys-dependencies-linux

      - name: Run sccache-cache
        uses: trustwallet/github-actions-proxy/actions/sccache-action@main

      - name: Install Rust dependencies
        run: |
          tools/install-rust-dependencies

      - name: Run codegen-v2 tests
        run: |
          cargo test --all
        working-directory: codegen-v2

      # Generate files for a blockchain.
      # Please note the blockchain should not be implemented in Rust at the moment of running this step,
      # otherwise consider either generating files for another blockchain or removing this step at all.
      - name: Test codegen-v2 new-blockchain-rust
        run: |
          cargo run -- new-blockchain-rust iotex
        working-directory: codegen-v2

      # Check if `new-blockchain-rust` command has generated files that do not break project compilation.
      - name: Check Rust compiles
        run: |
          cargo check --tests
        working-directory: rust
