name: Docker CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
    paths:
      - Dockerfile
      - tools/install-dependencies

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Lint Dockerfile
        run: |
          curl -L https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-Linux-x86_64 -o hadolint && chmod +x hadolint
          ./hadolint Dockerfile
      - name: Build Dockerfile
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6.19.2
        with:
          repository: trustwallet/wallet-core
          tags: latest
          push: false
