name: Docker CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
    paths:
      - Dockerfile
      - tools/install-dependencies

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Lint Dockerfile
        run: |
          curl -L https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-Linux-x86_64 -o hadolint && chmod +x hadolint
          ./hadolint Dockerfile
      - name: Build Dockerfile
        uses: docker/build-push-action@92e71463491f2d026a477188b8ad3a0fdd9d672c # v1.1.0
        with:
          repository: trustwallet/wallet-core
          tags: latest
          push: false
