name: Tangem - Publish

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DVELOPMENT_ANDROID }}

jobs:
  create_tag:
    name: Create tag
    id: create_tag
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read version.properties file
        uses: BrycensRanch/read-properties-action@v1
        id: version
        with:
          file: version.properties
          property: tangem
          default: 0.0.1-tangem1

      - name: Echo version.properties
        run: echo publish-version
        with:
          publish-version: ${{ steps.version.outputs.tangem }}

      - name: Create tag
        uses: actions/github-script@v3
        if: False # temporarily disabled
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.version.outputs.tangem }}",
              sha: context.sha
            })
    outputs:
      publish_version: ${{ steps.version.outputs.tangem }}

  publish_ios:
    name: Publish iOS
    runs-on: macos-latest
    needs: create_tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Echo version.properties
        run: echo ${{ needs.create_tag.outputs.publish_version }}

  publish_android:
    name: Publish Android
    runs-on: macos-latest
    needs: create_tag
    if: False # temporarily disabled
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install system dependencies
        run: |
          tools/install-sys-dependencies-mac

      - name: Install Android Dependencies
        run: tools/install-android-dependencies

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            rust

      - name: Install Rust dependencies
        run: |
          tools/install-rust-dependencies

      - name: Cache internal dependencies
        id: internal_cache
        uses: actions/cache@v3
        with:
          path: build/local
          key: ${{ runner.os }}-${{ runner.arch }}-internal-${{ hashFiles('tools/install-dependencies') }}

      - name: Install internal dependencies
        run: tools/install-dependencies
        if: steps.internal_cache.outputs.cache-hit != 'true'

      - name: Generate files
        run: tools/generate-files android

      - name: Build and publish Android
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        run: |
          cd android/
          echo sdk.dir = $ANDROID_HOME > local.properties
          GITHUB_USER=${{ secrets.GITHUB_ACTOR }} GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./gradlew build assembleRelease publish -Pversion=${{ needs.create_tag.outputs.publish_version }}
