name: Wasm CI

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: Install system dependencies
      run: |
        tools/install-sys-dependencies-linux
        tools/install-rust-dependencies
    - name: Install emsdk
      run: tools/install-wasm-dependencies

    - name: Cache internal dependencies
      id: internal_cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: build/local
        key: ${{ runner.os }}-${{ runner.arch }}-internal-${{ hashFiles('tools/install-dependencies') }}-${{ hashFiles('tools/dependencies-version') }}

    - name: Install internal dependencies
      run: tools/install-dependencies
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++
      if: steps.internal_cache.outputs.cache-hit != 'true'

    - name: Code generation
      run: |
        source emsdk/emsdk_env.sh
        tools/generate-files wasm
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++

    - name: Build for Wasm
      run: |
        source emsdk/emsdk_env.sh
        tools/wasm-build
      env:
        CC: /usr/bin/clang
        CXX: /usr/bin/clang++

    - name: Fetch Nexus User Auth Credentials
      id: fetch_nexus_credentials
      uses: trustwallet/devops/ci/actions/nexus-token-fetcher@main
      with:
        nexus_url: https://nexus.twinternal.net
        nexus_username: ${{ secrets.NEXUS_USERNAME }}
        nexus_password: ${{ secrets.NEXUS_PASSWORD }}

    - name: Configure npmrc file
      run: |
        NEXUS_AUTH_TOKEN=$(echo -n "${{ steps.fetch_nexus_credentials.outputs.nexus_token_username }}:${{ steps.fetch_nexus_credentials.outputs.nexus_token_password }}" | base64)
        cat > ~/.npmrc << EOF
        registry=https://nexus.twinternal.net/repository/trust-sdk-npm/
        //nexus.twinternal.net/repository/trust-sdk-npm/:_auth=${NEXUS_AUTH_TOKEN}
        EOF

    - name: Test
      run: |
        npm install --loglevel=verbose && npm run build-and-test
      working-directory: wasm

    - name: Cleanup npmrc
      if: always()
      run: |
        rm -f ~/.npmrc
        rm -f .npmrc